Fixing error that occurs when starting a site
Error that I encountered:

File "...Assignment1\craft-bots\craftbots\entities\site.py", line 29, in __init__
    if task.node == self.node and task.project is None:
AttributeError: 'Task' object has no attribute 'project'

I propose changing task.project to task.linked_site, this fixed the error for me.